### PR TITLE
Revert tx arrays, add delegate discovery and links

### PR DESCRIPTION
**Pull request by sheerlox**

### CODE REVIEW

**Review by dakk — COMMENTED** [review]
Why did you reverse the txlist? We need to display recent txs first

**Comment by sheerlox** [comment]
Woops my bad

**Comment by sheerlox** [comment]
I will remove this

**Comment by sheerlox** [comment]
@dakk removed

**Review by dakk — APPROVED** [review]

**Comment by sheerlox** [comment]
@dakk there is something weird ... on LIG website without reversing txs display the recents txs first, but on lisk-france.fr this is reversed :confused:

**Comment by dakk** [comment]
mmh really weird..

**Pull request merged**
